# Generated by Django 3.1 on 2020-08-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frivacyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('owner', models.CharField(max_length=20)),
                ('content', models.CharField(default='', max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=20)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('sign_up_date', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('profilepic', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'test_user',
            },
        ),
    ]
