# Generated by Django 3.1 on 2020-08-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frivacyApp', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.CharField(max_length=20)),
                ('type0', models.IntegerField(default=0)),
                ('type1', models.IntegerField(default=0)),
                ('type2', models.IntegerField(default=0)),
                ('type3', models.IntegerField(default=0)),
                ('type4', models.IntegerField(default=0)),
                ('type5', models.IntegerField(default=0)),
            ],
        ),
    ]
