# Generated by Django 3.1 on 2020-08-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frivacyApp', '0008_auto_20200820_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('place', models.CharField(default='', max_length=255)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('content', models.CharField(default='', max_length=255)),
                ('add1', models.CharField(default='', max_length=255)),
                ('add2', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
