# Generated by Django 3.1 on 2020-08-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frivacyApp', '0009_fest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='a1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='a2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
